### ISSUE TITLE
Adding new air-frame for multicopter.

### ISSUE THREAD

**Issue by chuong98** [PX4/PX4-Devguide#435]
We want to do an experiment with a new configuration, as illustrated in the Fig 
![quad_ct](https://user-images.githubusercontent.com/15174756/35171738-1914d738-fd22-11e7-98b0-088b63ce08fb.png)
The idea is: 
M1 is the big motor at the Center of the Gravity to create 99% thrust, and facing down.
M2 is small motor to control positive pitch, facing up
M3,M4 are the small motor, M2 tilts 45deg, and M4 tilts -45deg, to create yaw moment to balance with the big motor, while also control roll and pitch. 

Take the center motor at the origin, and follow NED coordinate, the position of motor is
#motor  (x,y,z)         (direction in (x,y,z) )
M1        (0,0,0)              (0,0,1)
M2       (-R,0,0)             (0,0,-1)
M3       (-R/2,R,0)   (cos(45),0, -cos(45))
M4       (-R/2,R,0)   (-cos(45), 0,-cos(45))

I would like to create quad_cT config in the mixer file, how should I do it. Thanks for your help.

**Comment by dagar** [comment]
@jlecoeur FYI

**Comment by jlecoeur** [comment]
@chuong98 cool design! If I may suggest something, M3 and M4 will create more pitch moment than M2 so you should either place M3 and M4 closer to the CG, or tilt them at 60° instead of 45°. 

## Step 1 Geometry
### 1-a Geometry file
Add a geometry file in the folder `src/lib/mixer/geometries/` named **quad_ct.toml** with the following content:
```toml
# Experimental multirotor

[info]
key = "4ct"
description = "Experimental multirotor"

[rotor_default]
direction = "CW"
axis      = [0.0, 0.0, -1.0]
Ct        = 1.0
Cm        = 0.05

[[rotors]]
name      = "M1"
position  = [0.0, 0.0, 0.0]
Ct = 100
Cm = 5

[[rotors]]
name      = "M2"
position  = [-1.0, 0.0, 0.0]
direction = "CCW"

[[rotors]]
name     = "M3"
position = [0.5, -1.0, 0.0]
axis = [0.7071, 0.0, -0.7071]
direction = "CCW"

[[rotors]]
name     = "M4"
position = [0.5, 1.0, 0.0]
axis = [-0.7071, 0.0, -0.7071]
direction = "CCW"
```
Ct are the  thrust coefficients and Cm are moment coefficients, I put arbitrarily larger values for M1 but you will have to adjust it to your motors. For this you can measure the thrust ratio between M1 and M2 and use the same ratio for the respective Ct-s. Same thing for the moment coefficients.

### 1-b Cmakelists
Add quad_ct.toml to the geometry list here:
https://github.com/PX4/Firmware/blob/master/src/lib/mixer/CMakeLists.txt#L45
